env:
  browser: true
  jest: true
  es6: true
  node: true

extends:
  - 'eslint:recommended'

parser: 'babel-eslint'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 8
  sourceType: module

plugins:
  - react

rules:

  react/prop-types:
    - 0
  react/jsx-uses-react:
    - 1
  react/jsx-uses-vars:
    - 1
  react/jsx-tag-spacing:
    - 1

  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  object-curly-spacing:
    - warn
    - always
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - 1
  no-multiple-empty-lines:
    - warn
  no-multi-spaces:
    - warn
  key-spacing:
    - warn
  comma-spacing:
    - warn
  max-len:
    - 1
    - 100
